version: "3.6"
services:
  remember_code:
    build: "../.."
    restart: always
    ports:
      - "8080"
    container_name: "remember_code_rest"
  nginx:
    build: "../../nginx"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "remember_code"
    container_name: "nginx"
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - /Users/joy/data/mongo:/data/db
    container_name: "mongodb"
