version: "3.6"
services:
  remember_code:
    image: joylucky/remember_code:1.0
    restart: always
    ports:
      - "8080"
    container_name: "remember_code_rest"
  nginx:
    image: joylucky/remember_code_nginx:1.0
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "remember_code"
    container_name: "nginx"
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    container_name: "mongodb"
